### ISSUE TITLE
Have an overview of all the possible scripts or commands we can execute once backdoor is installed

### ISSUE THREAD

**Issue by Dilkovak** [pyppek/motherducker#51]

**Comment by Dwalde** [comment]
Generated a list of Windows Management Instrumentation (WMI) objects we can use to gather (and possibly alter) information from (and on) infected machines, and highlighted some of the more useful properties from each WMI-object. Gathered hardware WMI objects and started analyzing their properties.

**Comment by Dwalde** [comment]
Hardware WMI objects analyzed. Results are in the "Powershell Command Overview" word document, I have bolded the properties I think we'll find most useful. I'll look into how to make scripts that take properties from different objects and saves them into a hashtable
