### ISSUE TITLE
Secure coding practices

### ISSUE THREAD

**Issue by Dilkovak** [pyppek/motherducker#8]
Research what coding practices are the most secure when creating an application.

Maybe OWASP has some guidelines

**Comment by elzoops** [comment]
- [ ] https://www.owasp.org/images/0/08/OWASP_SCP_Quick_Reference_Guide_v2.pdf   : a 17 pages of checklist about securing codes requirements which are summarized in page 13
- [ ] An overview of Django's security features which provides advice on securing --Django-powered site: https://docs.djangoproject.com/en/2.2/topics/security/   
- [ ] Tips for making django Admin more secure : https://opensource.com/article/18/1/10-tips-making-django-admin-more-secure  
- [ ] 5 ways to make django Admin more secure : https://hackernoon.com/5-ways-to-make-django-admin-safer-eb7753698ac8   
- [ ] Common mistakes to avoid by developpers: https://hackernoon.com/7-common-mistakes-that-django-developers-make-8k5w33el
- [ ] Django web application security : securing your django web applications ( included features are HTLM, CSS, Accessibility, tools and testing, server-side website programming, and advanced learning material): https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/web_application_security
- [ ] Deployment(security)checklist: https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/
- [ ] Django 2.2.7 fixes severals bugs in 2.2.6 (version 2.2.7 being the latest): https://docs.djangoproject.com/en/2.2/releases/2.2.7/
